baseURL = '/'
languageCode = 'en-us'
title = 'KDebugger'
contentDir = "content"

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

# [[menu.primary]]
#     name  = "Docs"
#     url = "/docs/"
#     identifier = "docs"
#     weight = 10

[params]
    google_fonts = [
        ["Inter", "300, 400, 600, 700"],
        ["Fira Code", "500, 700"]
    ]

    sans_serif_font = "Inter"
    secondary_font = "Inter"
    mono_font = "Fira Code"

    [params.footer]
        copyright = "© :YEAR: SHIZO::GAMES"

    [params.docs]
        title = "KDebugger"

        themeColor = "cardinal"
        darkMode = true

        sidebarIcons = true
        titleIcon = true
        
        prims = true
        prismTheme = "twilight"
    
        breadcrumbs = true

        extLinkNewTab = true

        descriptions = true

        toc = true
        tocMobile = true
        scrollSpy = true